14:04:08 UploadAttachment_ContentId:nEgaKAKlXqwOAjyMTWYJ:{"Message":"ORA-00604: error occurred at recursive SQL level 1\nORA-01013: user requested cancel of current operation\nORA-06512: at \"SYS.DBMS_LOCK\", line 82\nORA-06512: at \"SYS.DBMS_LOCK\", line 98\nORA-06512: at \"CTXSYS.DRIDML\", line 50\nORA-06512: at \"CTXSYS.DRIDML\", line 84\nORA-06512: at \"CTXSYS.DRVDDL\", line 5398\nORA-06512: at \"CTXSYS.DRVDML\", line 687\nORA-06512: at line 1","StackTrace":"   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)\r\n   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)\r\n   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()\r\n   at UCMS.Core.OracleHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, OracleParameter[] parameters) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Core\\OracleHelper.cs:line 60\r\n   at UCMS.Data.DataAdapter.Oracle.OcAttachmentDataAdapter.CommitBatch(List`1 batch) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Data\\DataAdapter\\Oracle\\OcAttachmentDataAdapter.cs:line 72\r\n   at UCMS.Services.ContentTransactionService.Commit(Content content) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.Services\\ContentTransactionService.cs:line 109\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__1() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 267\r\n   at UCMS.WebAPI.Controllers.ContentController.<>c__DisplayClass12_0.<CheckIn>b__0() in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\ContentController.cs:line 262\r\n   at UCMS.WebAPI.Controllers.BaseApiController.Execute[TResult](Func`1 action, Boolean logRequest) in D:\\Projects\\UCMS_VIB\\UCMS\\UCMS.WebAPI\\Controllers\\BaseApiController.cs:line 114\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}
